### ISSUE TITLE
Selector Boundary Color and Boundary Size not present in the library when installed from Gradle

### ISSUE THREAD

**Issue by shubham192** [oli107/material-range-bar#100]
The selector properties of `selectorBoundaryColor` and `selectorBoundarySize` are not present in the java code when installing from the `Gradle` file.
I see those properties were added in the recent commits. Are they going to be included in the next version?

**Comment by theBlbDan** [comment]
Bump!  Would really like to see the documentation as well.  I'm enjoying the library, so thanks for putting it together.

**Comment by krazykira** [comment]
This was fixed in the last version. Please check Readme.md file for details
