### ISSUE TITLE
Not easy to set right to same value of left when there are a lot of ticks

### ISSUE THREAD

**Issue by johnpeb** [oli107/material-range-bar#101]
For example if one makes a one sided slider (seek?) from 0 to 100 it is not east to select exactly 0. One has to move the point very carefully and slowly to the left in order to select 0 value. 

Reproducible in the demo app:
- press range/seek
- tickStart = 0
- tickEnd = 100
- tickInterval = 1 or < 1
- drag the point and try to select 0. Usually it stops moving when right = 1, 2, or 3

**Comment by maxwell10206** [comment]
Any solution?

**Comment by maxwell10206** [comment]
#112 I think I figured out the issue. See my pull request.

**Comment by krazykira** [comment]
Fixed in version 1.4.3
