### ISSUE TITLE
Error:(144) No resource identifier found for attribute...

### ISSUE THREAD

**Issue by MiguelRossi** [oli107/material-range-bar#105]
When importing the widget using gradle ('com.appyvet:materialrangebar:1.3') it doesn't sync the project showing these three errors:

property | error
---|---
*custom:barPaddingBottom* | Error:(144) No resource identifier found for attribute 'barPaddingBottom' in package 'my.secret.project'
*custom:selectorBoundaryColor* | Error:(144) No resource identifier found for attribute 'selectorBoundaryColor' in package 'my.secret.project'
*custom:selectorBoundarySize* | Error:(144) No resource identifier found for attribute 'selectorBoundarySize' in package 'my.secret.project'

Related issues:
https://github.com/oli107/material-range-bar/issues/104
https://github.com/oli107/material-range-bar/issues/100

**Comment by krazykira** [comment]
There will be a new release very soon which will have `selectorBoundaryColor` and `selectorBoundarySize` properties
Regarding `barPaddingBottom` it is suppose to be `rangeBarPaddingBottom` in `version 1.3` the Readme.md is probably outdated

**Comment by MiguelRossi** [comment]
Thanks
