### ISSUE TITLE
Cant import the RangeBar class

### ISSUE THREAD

**Issue by felipecastilhos** [oli107/material-range-bar#109]
Hi,

I did add the dependency in my gradle file:

 compile 'com.appyvet:materialrangebar:1.3'

in my class when I try to use the RangeBar it says "Cannot Resolve symbol Rangebar" but I can use it in my XML and use the properties normally.

**Comment by theBlbDan** [comment]
Did you add
```import com.appyvet.rangebar.RangeBar;```
to your class file you are trying to use it in?

**Comment by felipecastilhos** [comment]
I do not remember how I solve it. But it was something way more complex than that. haha
