### ISSUE TITLE
Pins are initially showed even if temporaryPins is true

### ISSUE THREAD

**Issue by bryant1410** [oli107/material-range-bar#12]

**Comment by oli107** [comment]
Please provide more info, if temporary pins is true one expects the pins to appear and disappear when touched. This seems to work as expected?

**Comment by bryant1410** [comment]
Oh, I though this wasn't the expected behavior

**Comment by oli107** [comment]
You're correct, now fixed in 1.3, pushing now

**Comment by bryant1410** [comment]
:+1:
