### ISSUE TITLE
Request : foreverPins

### ISSUE THREAD

**Issue by kwiky** [oli107/material-range-bar#14]
I have a request : always show the pins with values, even when user don't drag it. (poke @jkwiecien who have made a good work with temporaryPins)

**Comment by Shivam-Miglani** [comment]
can do by attribute
custom:temporaryPins = "false"

**Comment by oli107** [comment]
I haven't tested this, does it work?

**Comment by kwiky** [comment]
custom:temporaryPins = "false" means that you never want display pins ? no ? 
Already tried

**Comment by kwiky** [comment]
I get it !

temporaryPins are canceled in createPins
wich is call in setRangePinsByValue

Same issue with formater that i fix here https://github.com/oli107/material-range-bar/pull/35
