### ISSUE TITLE
where are the dimens in the sample?

### ISSUE THREAD

**Issue by BugsBunnyBR** [oli107/material-range-bar#17]
I can't find the @dimens in the file
https://github.com/oli107/material-range-bar/blob/master/RangeBarSample/res/drawable/material_button.xml

**Comment by oli107** [comment]
in dimens_material.xml
sample was made ages ago before appcompat was what it is now. Feel free to improve!

**Comment by BugsBunnyBR** [comment]
There is no such file in the project.
