### ISSUE TITLE
Thumbs are cropped in the edges if pinRadius == 0

### ISSUE THREAD

**Issue by WonderCsabo** [oli107/material-range-bar#20]
If thumbs are at the end of the range bar and the pin size is 0dp, then the thumbs are cropped.

![screen shot 2015-11-10 at 11 21 59](https://cloud.githubusercontent.com/assets/480485/11059951/4b6bab28-879d-11e5-9fb2-e5f084b1ccfd.png)

**Comment by oli107** [comment]
have you tried putting some padding into the view?

**Comment by WonderCsabo** [comment]
Of course, and padding has absolutely zero effect on the rangebar. :(

**Comment by oli107** [comment]
OK, fixed in 1.3

**Comment by WonderCsabo** [comment]
Thanks very much. I will check it out tomorrow.

**Comment by WonderCsabo** [comment]
This works thanks.
