### ISSUE TITLE
Give user the ability to set Maximium and Minimum Pin font size

### ISSUE THREAD

**Issue by rstel** [oli107/material-range-bar#21]
It would be a nice feature to allow the user to define what the maximum and minimum Pint texts font size. I have noticed that when a Pins text contains 2 characters the font size shrinks. I believe it would be more aesthetic if the font size was the same throughout and let the user decide.

It seems as though if you let the user change 
mMinPinFont 
https://github.com/oli107/material-range-bar/blob/master/rangebar/src/com/appyvet/rangebar/PinView.java#L88

and 
mMaxPinFont 
https://github.com/oli107/material-range-bar/blob/master/rangebar/src/com/appyvet/rangebar/PinView.java#L90

It would allow the user to define the right size that works for them.

Or implement a variable that if set, sets the font size of the text.

**Comment by oli107** [comment]
This can be set by XML parameter, do you mean a way to set it programmatically?

**Comment by rstel** [comment]
Would that be by using the pinPadding property?

**Comment by oli107** [comment]
pinMaxFont and pinMinFont
On 12 Nov 2015 00:14, "rstel" <notifications@github.com> wrote:

> Would that be by using the pinPadding property?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oli107/material-range-bar/issues/21#issuecomment-155954607>
> .
>

-- 


*## **Email confidentiality notice **##*

*This message is private and confidential. If you have received this 
message in error, please notify us and remove it from your 
system. Blythwood Vets & The Well Animal Clinic may monitor email traffic 
data and also the content of email for the purposes of security.*

*Blythwood Vets is the name under which the surgeries at Bushey, Northwood, 
Stanmore & Hatch End trade but the surgeries are owned by Blythwood 
Veterinary Ltd, a Limited Liability Company registered in England with 
Company No. 07153623, registered office 500 Uxbridge Road, Pinner, Middx, 
HA5 4SL or; in the case of the Bushey surgery, Blythwood Veterinary 
(Bushey) LLP, a Limited Liability Partnership registered in England with 
No. oc368295, registered office 2 High Street, Bushey, Herts WD23 3DN.*

*Well Animal Clinic is the trading name of Well Animal Clinic LLP, a 
Limited Liability Partnership registered in England with No. oc317137, 
registered office 292 West End Lane, London NW6 1LN.*

*A list of members each LLP is open to inspection at their respective 
registered offices.*

*BLYTHWOOD VETS& THE WELL ANIMAL CLINIC*

*“A COMPLETE CARING SERVICE FOR YOUR PET”*

*Visit us at: **www.blythwood.com* <http://www.blythwood.com/>* & **www.wellanimalclinic.com 
<http://www.wellanimalclinic.com/>*

**Comment by rstel** [comment]
Oh okay. I'd consider this complete then once the Readme pin properties is updated to reflect those properties.Unless you feel as though there should be a way to do it programmatically.
