### ISSUE TITLE
IllegalArgumentException: Pin value

### ISSUE THREAD

**Issue by donpironet** [oli107/material-range-bar#28]
On some devices I get crashes like this:

Fatal Exception: java.lang.IllegalArgumentException: Pin value left 0.0, or right 120.0 is out of bounds. Check that it is greater than the minimum (0.0) and less than the maximum value (100.0)

How can I avoid this? Because when I test it on all my devices that I have I never get that exception? I can't see how they can slide so far to the right that it goes over the max because the UI doesn't let you do that?

**Comment by oli107** [comment]
Somewhere you are setting the pin value to greater than the range programatically.
