### ISSUE TITLE
touching outside the range bar(move action) ...extends the bar and pin out of range .

### ISSUE THREAD

**Issue by rameen** [oli107/material-range-bar#39]

**Comment by subediaayush** [comment]
any progress on this?? having the same issue

**Comment by swbradshaw** [comment]
+1 I'm seeing the same issue

**Comment by mpetlyuk** [comment]
+1

**Comment by dgelormini** [comment]
![image](https://user-images.githubusercontent.com/7606358/41012657-a3b8d7ea-6910-11e8-9ceb-0eb34f240ed6.png)
+1 This sounds like my issue

**Comment by krazykira** [comment]
Fixed in version #137
