### ISSUE TITLE
Worst lib I ever seen

### ISSUE THREAD

**Issue by vasiledoe** [oli107/material-range-bar#80]
Nothing works properly, values are donated when I am getting left/right index also it goes out of range if you move it to the end couple of times also it not support setRangePinsByIndices(x,y) properly... in one word - it' a big bit SHIT!

**Comment by glureau** [comment]
Then what do you take time to create an issue? Is it just to spit your frustration? (Hint: nobody cares)

If you've something better, please share. Or maybe help on the project to build something better, but do something constructive please...

**Comment by qymspace** [comment]
The guys doesnt have any proper repositories. He should just shut up.
